### ISSUE TITLE
WandB hangs at the end of multi-gpu DDP training

### ISSUE THREAD

**Issue by mnoukhov** [facebookresearch/fairseq#4619]
## 🐛 Bug

If you train with multigpu using ddp while logging with `wandb`, then the program doesn't exit as wandb hangs because there is no `wandb.finish()` call. 

See https://docs.wandb.ai/guides/track/advanced/distributed-training#hanging-at-the-end-of-training

### To Reproduce

1. Run any regular training method with multiple gpus e.g. translation from `fairseq/examples/backtranslation`  

2. After the training finishes, the program does not exit

3. On killing the program (e.g. with Control+C) you get a stack trace about multiprocessing

```bash
2022-07-29 22:52:33 | INFO | fairseq_cli.train | done training in 162.1 seconds
^CTraceback (most recent call last):
  File "/mnt/home/miniconda/envs/fairseq/lib/python3.7/runpy.py", line 193, in _run_module_as_main
Process SpawnProcess-1:
    "__main__", mod_spec)
  File "/mnt/home/miniconda/envs/fairseq/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/home/fairseq/fairseq_cli/train.py", line 570, in <module>
    cli_main()
  File "/mnt/home/fairseq/fairseq_cli/train.py", line 563, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/mnt/home/fairseq/fairseq/distributed/utils.py", line 351, in call_main
    join=True,
  File "/mnt/home/miniconda/envs/fairseq/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/mnt/home/miniconda/envs/fairseq/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
Traceback (most recent call last):
  File "/mnt/home/miniconda/envs/fairseq/lib/python3.7/multiprocessing/process.py", line 300, in _bootstrap
    util._exit_function()
  File "/mnt/home/miniconda/envs/fairseq/lib/python3.7/multiprocessing/util.py", line 357, in _exit_function
    p.join()
  File "/mnt/home/miniconda/envs/fairseq/lib/python3.7/multiprocessing/process.py", line 140, in join
    res = self._popen.wait(timeout)
  File "/mnt/home/miniconda/envs/fairseq/lib/python3.7/multiprocessing/popen_fork.py", line 48, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/mnt/home/miniconda/envs/fairseq/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
    while not context.join():
  File "/mnt/home/miniconda/envs/fairseq/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 111, in join
    timeout=timeout,
  File "/mnt/home/miniconda/envs/fairseq/lib/python3.7/multiprocessing/connection.py", line 921, in wait
KeyboardInterrupt
    ready = selector.select(timeout)
  File "/mnt/home/miniconda/envs/fairseq/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
Traceback (most recent call last):
  File "run_on_snow.py", line 90, in <module>
    subprocess.run(command, shell=True, check=True, text=True)
  File "/opt/conda/lib/python3.7/subprocess.py", line 490, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/opt/conda/lib/python3.7/subprocess.py", line 956, in communicate
    self.wait()
  File "/opt/conda/lib/python3.7/subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "/opt/conda/lib/python3.7/subprocess.py", line 1653, in _wait
    (pid, sts) = self._try_wait(0)
  File "/opt/conda/lib/python3.7/subprocess.py", line 1611, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

#### Code sample

From `fairseq/examples/backtranslation`

```bash
CHECKPOINT_DIR=checkpoints_en_de_parallel
CUDA_VISIBLE_DEVICES=0,1 fairseq-train --fp16 \
    data-bin/wmt18_en_de \
    --source-lang en --target-lang de \
    --arch transformer_wmt_en_de_big --share-all-embeddings \
    --dropout 0.3 --weight-decay 0.0 \
    --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr 0.001 --lr-scheduler inverse_sqrt --warmup-updates 4000 \
    --max-tokens 3584 --update-freq 16 \
    --max-update 2 \
    --save-dir $CHECKPOINT_DIR \
    --ddp-backend no_c10d \ 
    --wandb-project MYWANDBPROJECT
```

Program will finish training and then hang.

### Expected behavior

Program should exit after training

### Environment

 - fairseq Version (e.g., 1.0 or main): main
 - PyTorch Version 
 - OS (e.g., Linux): Debian Linux
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source): pip install -e .
 - Python version: 3.7.6
 - CUDA/cuDNN version: 11.4
 - GPU models and configuration: 2x Tesla P100 (also tested with V100)

**Comment by parambharat** [comment]
@mnoukhov , Thanks for the issue and developing a quick fix. We have worked on a fix that enables [wandb service](https://docs.wandb.ai/guides/track/advanced/distributed-training#wandb-service) by default. This is in [pre-release](https://github.com/wandb/wandb/releases/tag/v0.13.0rc6) currently and can be installed using `pip install --pre --upgrade wandb`.

Could you confirm if the issue is resolved after installing the pre-release version ? Thanks in advance.

**Comment by mnoukhov** [comment]
That does solve it and seems like a much more elegant solution, thanks @parambharat
