### ISSUE TITLE
CUDA error of self.embed_positions

### ISSUE THREAD

**Issue by jiayidengYumy** [facebookresearch/fairseq#5381]
### Before asking:
1. search the issues.
2. search the docs.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or main):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:
I am running a Chinese BART LARGE on GEC task. I am using BertTokenizer to tokenize the raw Chinese text and use the checkpoint from huggingface to initialize the BART model. However, I get this bug.
./aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [168,0,0], thread: [28,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [168,0,0], thread: [29,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [168,0,0], thread: [30,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [168,0,0], thread: [31,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

**Comment by jiayidengYumy** [comment]
I have finished working on it. Since my training sentences were too long, extending the length of the max position embeddings led to a CUDA index error. However, after setting the truncate dataset parameters, I was able to solve the problem.
